/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ra2257075
 */
public class FormEstado extends javax.swing.JFrame {

    /**
     * Creates new form FormEstado
     */
    public FormEstado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelONU = new javax.swing.JLabel();
        lbl_nomeEstado = new javax.swing.JLabel();
        txt_nomeEstado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbl_liderEstado = new javax.swing.JLabel();
        txt_liderEstado = new javax.swing.JTextField();
        lbl_pibEstado = new javax.swing.JLabel();
        spin_pibEstado = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_classePais = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_nomeEstado1 = new javax.swing.JLabel();
        btn_cadastrarEstado = new javax.swing.JButton();
        btn_editarEstado = new javax.swing.JButton();
        btn_editarEstado1 = new javax.swing.JButton();
        btn_cancelarEstado = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 318));

        labelONU.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 24)); // NOI18N
        labelONU.setText("ORGANIZAÇÃO DAS NAÇÕES UNIDAS");

        lbl_nomeEstado.setFont(new java.awt.Font("Source Sans Pro Light", 0, 18)); // NOI18N
        lbl_nomeEstado.setText("Sistema Único de Registro de Tratados e Estados-Nação");

        txt_nomeEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeEstadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do País");

        lbl_liderEstado.setText("Líder do País");

        txt_liderEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_liderEstadoActionPerformed(evt);
            }
        });

        lbl_pibEstado.setText("PIB Estimado");

        jLabel4.setText("Classe");

        cmb_classePais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado pobre", "Estado marginalizado", "Estado rico", "Potencia", "Superpotencia" }));
        cmb_classePais.setSelectedItem(txt_nomeEstado);
        cmb_classePais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_classePaisActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lbl_nomeEstado1.setFont(new java.awt.Font("Source Sans Pro Light", 0, 14)); // NOI18N
        lbl_nomeEstado1.setText("Registro de Estados-Nação e Comunidades ");

        btn_cadastrarEstado.setBackground(new java.awt.Color(0, 153, 0));
        btn_cadastrarEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cadastrarEstado.setText("Cadastrar");
        btn_cadastrarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarEstadoActionPerformed(evt);
            }
        });

        btn_editarEstado.setBackground(new java.awt.Color(255, 102, 0));
        btn_editarEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_editarEstado.setText("Editar");
        btn_editarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarEstadoActionPerformed(evt);
            }
        });

        btn_editarEstado1.setBackground(new java.awt.Color(255, 0, 0));
        btn_editarEstado1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_editarEstado1.setText("Excluir");
        btn_editarEstado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarEstado1ActionPerformed(evt);
            }
        });

        btn_cancelarEstado.setBackground(new java.awt.Color(153, 153, 153));
        btn_cancelarEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cancelarEstado.setText("Cancelar");
        btn_cancelarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nomeEstado)
                            .addComponent(labelONU)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(lbl_liderEstado)
                                    .addComponent(txt_liderEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(txt_nomeEstado))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spin_pibEstado)
                                    .addComponent(cmb_classePais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(lbl_pibEstado))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btn_cadastrarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_editarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_editarEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cancelarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)))
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(lbl_nomeEstado1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelONU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nomeEstado)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_nomeEstado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbl_pibEstado))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spin_pibEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_liderEstado)
                            .addComponent(jLabel4))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_liderEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_classePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cadastrarEstado)
                            .addComponent(btn_editarEstado)
                            .addComponent(btn_editarEstado1)
                            .addComponent(btn_cancelarEstado))
                        .addGap(5, 5, 5)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeEstadoActionPerformed

    private void txt_liderEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_liderEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_liderEstadoActionPerformed

    private void cmb_classePaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_classePaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_classePaisActionPerformed

    private void btn_cadastrarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadastrarEstadoActionPerformed

    private void btn_editarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarEstadoActionPerformed

    private void btn_editarEstado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarEstado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarEstado1ActionPerformed

    private void btn_cancelarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEstado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrarEstado;
    private javax.swing.JButton btn_cancelarEstado;
    private javax.swing.JButton btn_editarEstado;
    private javax.swing.JButton btn_editarEstado1;
    private javax.swing.JComboBox<String> cmb_classePais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelONU;
    private javax.swing.JLabel lbl_liderEstado;
    private javax.swing.JLabel lbl_nomeEstado;
    private javax.swing.JLabel lbl_nomeEstado1;
    private javax.swing.JLabel lbl_pibEstado;
    private javax.swing.JSpinner spin_pibEstado;
    private javax.swing.JTextField txt_liderEstado;
    private javax.swing.JTextField txt_nomeEstado;
    // End of variables declaration//GEN-END:variables
}
